id = "cairo"
name = "Cairo"
version = "0.1.2"
schema_version = 1
authors = [
    "Thomas Robert Butler IV trbiv@proton.me",
    "Okhai Omotuebe okhaio@protonmail.com",
    "Franco 0xpantera@proton.me",
]
description = "Cairo language support for Zed"
repository = "https://github.com/trbutler4/zed-cairo"

[grammars.cairo]
repository = "https://github.com/starkware-libs/tree-sitter-cairo"
rev = "8dcd77dbe7f68b2cc661031dff224dfc17bdbaf4"

[language_servers.cairo]
name = "Cairo Language Server"
languages = ["Cairo"]

[[capabilities]]
kind = "process:exec"
command = "scarb"
args = ["cache", "path"]
